######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 7 09:44:16 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
